---
- name: Deploy monitoring infrastructure
  hosts: localhost
  tasks:    
    - name: Deploy Prometheus
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus:latest
        network_mode: host
        volumes:
          - "./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
        state: started
        restart_policy: always
    
    - name: Deploy Grafana
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana:latest
        network_mode: host
        env:
          GF_SERVER_HTTP_PORT: "3001"  # Set Grafana to use port 3001
        volumes:
          - "grafana_data:/var/lib/grafana"
        state: started
        restart_policy: always

