global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 20s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'jenkins'
    metrics_path: '/prometheus/'
    scrape_interval: 30s
    scrape_timeout: 25s 
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8090']


 