# File: k8s/01-configs.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: "db"
  DB_NAME: "appdb"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_USER: "user"
  DB_PASSWORD: "user@1234"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init.sql: |
    -- MySQL initialization script
    CREATE TABLE IF NOT EXISTS test (
      id INT AUTO_INCREMENT PRIMARY KEY,
      message VARCHAR(255) NOT NULL
    );
    INSERT INTO test(message) VALUES('Database Initialized');
